In [5]:
import numpy as np
import cvxpy as cp

In [12]:
def c(p,m,q,z):
    return p/m*q - (p*q+(1-p)*z)

combos = set([(c(p,m,q,z), (p/m-1), (p/m*r - c(p,m,q,z) -v)) for p in (0,1) for m in (0.01,1) for q in (0,1) for z in (0,1) for r in (0,1) for v in (0,1)])
combos

{(-1.0, -1.0, 0.0),
 (-1.0, -1.0, 1.0),
 (0.0, -1.0, -1.0),
 (0.0, -1.0, 0.0),
 (0.0, 0.0, -1.0),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0),
 (0.0, 99.0, -1.0),
 (0.0, 99.0, 0.0),
 (0.0, 99.0, 99.0),
 (0.0, 99.0, 100.0),
 (99.0, 99.0, -100.0),
 (99.0, 99.0, -99.0),
 (99.0, 99.0, 0.0),
 (99.0, 99.0, 1.0)}

In [15]:
combos_simple = set([(p/m-1, p/m*r-(p/m*q - (p*q+(1-p)*z))-v) for p in (0,1) for m in (0.01,1) for q in (0,1) for z in (0,1) for r in (0,1) for v in (0,1)])
combos_v = set([(p/m-1, p/m*r-(p/m*q - (p*q+(1-p)*z))) for p in (0,1) for m in (0.01,1) for q in (0,1) for z in (0,1) for r in (0,1)])

combos_new = set([(p/m-1-c(p,m,q,z), p/m*r-c(p,m,q,z)) for p in (0,1) for m in (0.01,1) for q in (0,1) for z in (0,1) for r in (0,1)])


In [16]:
for cx,cy in sorted(combos_v):
    print(f'1+({cx})*x+y*({+cy}-v)>=0')
print()
#print(sorted(combos_simple))
for cx,cy in sorted(combos_simple):
    print(f'1+({cx})*x+y*({+cy})>=0')
print()
for cx,cy in sorted(combos_new):
    print(f'1+({cx})*x+y*({+cy}-v)>=0')

1+(-1.0)*x+y*(0.0-v)>=0
1+(-1.0)*x+y*(1.0-v)>=0
1+(0.0)*x+y*(0.0-v)>=0
1+(0.0)*x+y*(1.0-v)>=0
1+(99.0)*x+y*(-99.0-v)>=0
1+(99.0)*x+y*(0.0-v)>=0
1+(99.0)*x+y*(1.0-v)>=0
1+(99.0)*x+y*(100.0-v)>=0

1+(-1.0)*x+y*(-1.0)>=0
1+(-1.0)*x+y*(0.0)>=0
1+(-1.0)*x+y*(1.0)>=0
1+(0.0)*x+y*(-1.0)>=0
1+(0.0)*x+y*(0.0)>=0
1+(0.0)*x+y*(1.0)>=0
1+(99.0)*x+y*(-100.0)>=0
1+(99.0)*x+y*(-99.0)>=0
1+(99.0)*x+y*(-1.0)>=0
1+(99.0)*x+y*(0.0)>=0
1+(99.0)*x+y*(1.0)>=0
1+(99.0)*x+y*(99.0)>=0
1+(99.0)*x+y*(100.0)>=0

1+(-1.0)*x+y*(0.0-v)>=0
1+(0.0)*x+y*(-99.0-v)>=0
1+(0.0)*x+y*(0.0-v)>=0
1+(0.0)*x+y*(1.0-v)>=0
1+(99.0)*x+y*(0.0-v)>=0
1+(99.0)*x+y*(100.0-v)>=0


In [6]:
G=np.array([
 (-1.0, -1.0, -1.0),
 (-1.0, -1.0, 0.0),
 (0.0, -1.0, -1.0),
 (0.0, -1.0, 0.0),
 (0.0, 99.0, -1.0),
 (0.0, 99.0, 100.0),
 (99.0, 99.0, -1.0),
 (99.0, 99.0, 100.0),
 ###
 (0.0, 0.0, -1.0),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0),
 (0.0, 99.0, 0.0),
 (0.0, 99.0, 99.0),
 (99.0, 99.0, 0.0),
 (99.0, 99.0, 99.0)
])

R = np.array([

])

G2=np.array([(-1.0, 0.0),
 (-1.0, 1.0),
 (0.0, 0.0),
 (0.0, 1.0),
 (99.0, -99.0),
 (99.0, 0.0),
 (99.0, 1.0),
 (99.0, 100.0)])

R2 = np.array([

])

In [7]:
z = cp.Variable(3)

for i,gi in enumerate(G):
    Gmi = np.concatenate((G[:i], G[i+1:]))
    #print(gi)
    obj = cp.Minimize(1+z.T@gi)
    cons = [1+Gmi@z >= 0.0]
    problem = cp.Problem(obj,cons)
    problem.solve()
    #if problem.value > 0.49:
    print(gi, problem.value)

[-1. -1. -1.] -0.9999999834570823
[-1. -1.  0.] -0.9999999834051565
[ 0. -1. -1.] -0.9999999834576057
[ 0. -1.  0.] -0.9999999834027733
[ 0. 99. -1.] -0.9999999921714251
[  0.  99. 100.] -0.9999999917600422
[99. 99. -1.] -0.9999999921713894
[ 99.  99. 100.] -0.9999999917619511
[ 0.  0. -1.] 5.686443538266417e-10
[0. 0. 0.] 1.0
[0. 0. 1.] 5.721119133994534e-10
[ 0. 99.  0.] 1.901335755505329e-10
[ 0. 99. 99.] 1.930569037966734e-10
[99. 99.  0.] 1.9013191021599596e-10
[99. 99. 99.] 1.9304813303477886e-10


In [8]:
z = cp.Variable(2)

for i,gi in enumerate(G2):
    Gmi = np.concatenate((G2[:i], G2[i+1:]))
    #print(gi)
    obj = cp.Minimize(1+z.T@gi)
    cons = [1+Gmi@z >= 0.5]
    problem = cp.Problem(obj,cons)
    problem.solve()
    #if problem.value > 0.49:
    print(gi, problem.value)

[-1.  0.] -inf
[-1.  1.] 6.992992851451163e-10
[0. 0.] 1.0
[0. 1.] 0.7487437203436901
[ 99. -99.] -inf
[99.  0.] 0.4999999999650564
[99.  1.] 0.4999999999653658
[ 99. 100.] -48.99999998526398


In [20]:
print('w,r,c')
for p in (0,1):
    for m in (0.01,1): 
        for q in (0,1):
            for z in (0,1):
                for r in (0,1):
                    print(p/m,r,c(p,m,q,z))

w,r,c
0.0 0 0.0
0.0 1 0.0
0.0 0 -1.0
0.0 1 -1.0
0.0 0 0.0
0.0 1 0.0
0.0 0 -1.0
0.0 1 -1.0
0.0 0 0.0
0.0 1 0.0
0.0 0 -1.0
0.0 1 -1.0
0.0 0 0.0
0.0 1 0.0
0.0 0 -1.0
0.0 1 -1.0
100.0 0 0.0
100.0 1 0.0
100.0 0 0.0
100.0 1 0.0
100.0 0 99.0
100.0 1 99.0
100.0 0 99.0
100.0 1 99.0
1.0 0 0.0
1.0 1 0.0
1.0 0 0.0
1.0 1 0.0
1.0 0 0.0
1.0 1 0.0
1.0 0 0.0
1.0 1 0.0


In [91]:
combos_all = set([(c(p,m,q,z), p/m-1, p/m*r-c(p,m,q,z)) for p in (0,1) for m in (0.01,1) for q in (0.,1) for z in (0.,1.) for r in (0,1)])
combos_all

{(-1.0, -1.0, 1.0),
 (0.0, -1.0, 0.0),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0),
 (0.0, 99.0, 0.0),
 (0.0, 99.0, 100.0),
 (99.0, 99.0, -99.0),
 (99.0, 99.0, 1.0)}

In [36]:
combos_easy = set([(c(p,m,q,z), p/m-1, p/m*r) for p in (0,1) for m in (0.01,1) for q in (0,1) for z in (0,1) for r in (q,)])
combos_easy

{(-1.0, -1.0, 0.0),
 (0.0, -1.0, 0.0),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0),
 (0.0, 99.0, 0.0),
 (99.0, 99.0, 100.0)}

In [92]:
G = np.array([(-1.0, -1.0, 0.0),
 (0.0, -1.0, 0.0),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0),
 (0.0, 99.0, 0.0),
 (0.0, 99.0, 100.0),
 (99.0, 99.0, 0.0),
 (99.0, 99.0, 100.0)])

F = np.array([(-1.0, -1.0, 0.0),
 (0.0, -1.0, 0.0),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0),
 (0.0, 99.0, 0.0),
 (99.0, 99.0, 100.0)])

H = np.array([(-1.0, -1.0, 1.0),
 (0.0, -1.0, 0.0),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0),
 (0.0, 99.0, 0.0),
 (0.0, 99.0, 100.0),
 (99.0, 99.0, -99.0),
 (99.0, 99.0, 1.0)])

H

array([[ -1.,  -1.,   1.],
       [  0.,  -1.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   1.],
       [  0.,  99.,   0.],
       [  0.,  99., 100.],
       [ 99.,  99., -99.],
       [ 99.,  99.,   1.]])

In [93]:
z = cp.Variable(3)

for v in (0,0.25,0.5,0.75,1):
    for z2 in (-0.5,-0.25,0,0.25,0.5):
        obj = cp.Maximize(cp.min(1+H@z-v*z[2]))
        problem = cp.Problem(obj,[ z[2]==z2])
        problem.solve()
        print(np.round(problem.value,2),np.round(z.value,2),np.round(v,2),np.round(z2,2),)

0.5 [-0.5  0.5 -0.5] 0 -0.5
0.75 [-0.25  0.25 -0.25] 0 -0.25
1.0 [0. 0. 0.] 0 0
1.0 [0.25 0.   0.25] 0 0.25
1.0 [ 0.5 -0.   0.5] 0 0.5
0.63 [-0.5  0.5 -0.5] 0.25 -0.5
0.81 [-0.25  0.25 -0.25] 0.25 -0.25
1.0 [0. 0. 0.] 0.25 0
0.94 [0.25 0.   0.25] 0.25 0.25
0.88 [ 0.5 -0.   0.5] 0.25 0.5
0.75 [-0.5  0.5 -0.5] 0.5 -0.5
0.88 [-0.25  0.25 -0.25] 0.5 -0.25
1.0 [0. 0. 0.] 0.5 0
0.88 [0.25 0.   0.25] 0.5 0.25
0.75 [ 0.5 -0.   0.5] 0.5 0.5
0.88 [-0.5  0.5 -0.5] 0.75 -0.5
0.94 [-0.25  0.25 -0.25] 0.75 -0.25
1.0 [-0.  0. -0.] 0.75 0
0.81 [0.25 0.   0.25] 0.75 0.25
0.63 [ 0.5 -0.   0.5] 0.75 0.5
1.0 [-0.5  0.5 -0.5] 1 -0.5
1.0 [-0.25  0.25 -0.25] 1 -0.25
1.0 [-0.  0. -0.] 1 0
0.75 [0.25 0.   0.25] 1 0.25
0.5 [ 0.5 -0.   0.5] 1 0.5


In [106]:
combos_0 = set([(p/m-1, p/m*r-c(p,m,q,z)-v) for p in (0,1) for m in (0.01,1) for q in (0.,) for z in (0.,) for r in (0,1) for v in (0,1)])
G0 = np.array(list(combos_0))

z = cp.Variable(2)

for i,gi in enumerate(G0):
    Gmi = np.concatenate((G0[:i], G0[i+1:]))
    obj = cp.Minimize(1+z.T@gi)
    cons = [1+Gmi@z >= 0.5]
    problem = cp.Problem(obj,cons)
    problem.solve()
    print(gi, problem.value)
    
Gred0 = G0[[2,5,6,8],:]
print()
for i,gi in enumerate(Gred0):
    Gmi = np.concatenate((Gred0[:i], Gred0[i+1:]))
    obj = cp.Minimize(1+z.T@gi)
    cons = [1+Gmi@z >= 0.5]
    problem = cp.Problem(obj,cons)
    problem.solve()
    print(gi, problem.value)

[0. 1.] 0.500000000432267
[0. 0.] 1.0
[-1.  0.] 5.0290528408325486e-09
[99. 99.] 0.5000000008526408
[99.  0.] 0.5000000008528989
[99. -1.] 4.00054434024355e-11
[-1. -1.] 5.138121483838631e-09
[ 0. -1.] 0.5000000004287547
[ 99. 100.] 4.056799340901307e-11

[-1.  0.] -49.499999889056916
[99. -1.] -inf
[-1. -1.] -49.4999998901928
[ 99. 100.] -inf


In [109]:
combos_non0 = set([(p/m-1, p/m*r-c(p,m,q,z)) for p in (0,1) for m in (0.01,1) for q in (0.,1.) for z in (0.,1.) for r in (0,1) for v in (0,1)])

G_non0 = np.array(list(combos_non0))

z = cp.Variable(2)

for i,gi in enumerate(G_non0):
    Gmi = np.concatenate((G_non0[:i], G_non0[i+1:]))
    obj = cp.Minimize(1+z.T@gi)
    cons = [1+Gmi@z >= 0.5, z[1]>=0]
    problem = cp.Problem(obj,cons)
    problem.solve()
    print(gi, problem.value)
    
Gred_non0 = G_non0[[3,6],:]
print()
for i,gi in enumerate(Gred_non0):
    Gmi = np.concatenate((Gred_non0[:i], Gred_non0[i+1:]))
    obj = cp.Minimize(1+z.T@gi)
    cons = [1+Gmi@z >= 0.5, z[1]>=0]
    problem = cp.Problem(obj,cons)
    problem.solve()
    print(gi, problem.value)

[0. 1.] 1.0000000001799407
[-1.  1.] 0.5000000033097689
[0. 0.] 1.0
[-1.  0.] -inf
[99.  0.] 0.4999999999535618
[99.  1.] 0.4999999999522997
[ 99. -99.] -inf
[ 99. 100.] 0.4999999999935354

[-1.  0.] -inf
[ 99. -99.] -inf


In [110]:
G_non0

array([[  0.,   1.],
       [ -1.,   1.],
       [  0.,   0.],
       [ -1.,   0.],
       [ 99.,   0.],
       [ 99.,   1.],
       [ 99., -99.],
       [ 99., 100.]])